/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ulabs.appui01.ui;

import static com.ulabs.appui01.common.Constant.DISPLAY_CONTENT_HEIGHT;
import static com.ulabs.appui01.common.Constant.DISPLAY_CONTENT_WIDTH;
import static com.ulabs.appui01.common.Constant.DISPLAY_MENU_HEIGHT;
import static com.ulabs.appui01.common.Constant.DISPLAY_MENU_WIDTH;
import static com.ulabs.appui01.common.Constant.DISPLAY_TOP_HEIGHT;
import static com.ulabs.appui01.common.Constant.DISPLAY_TOP_WIDTH;
import com.ulabs.appui01.lib.router.EventListener;
import com.ulabs.appui01.ui.views.PageUI01;
import com.ulabs.appui01.ui.views.PageUI02;
import java.awt.BorderLayout;
import static com.ulabs.appui01.common.Constant.DISPLAY_SCREEN_HEIGHT;
import com.ulabs.appui01.lib.router.Router;
import com.ulabs.appui01.ui.components.viewProfile.ViewUIProfile;

/**
 *
 * @author manuelguarniz
 */
public class UIMain extends javax.swing.JFrame implements EventListener {
    private boolean statusCollapseMenu = false;

    /**
     * Creates new form UIMain
     */
    public UIMain() {
        initComponents();
        resizing();
        showPage01();
        initialize();
    }
    
    private void initialize() {
        ViewUIProfile vprofile = new ViewUIProfile();
        vprofile.setSize(ViewUIProfile.WIDTH, ViewUIProfile.HEIGHT);
        vprofile.setLocation(0, 0);
        
        Router.route().events.subscribe("view-ui-profile", vprofile);
        
        pnlProfile.removeAll();
        pnlProfile.add(vprofile, BorderLayout.PAGE_START);
        pnlProfile.revalidate();
        pnlProfile.repaint();
    }
    
    private void resizing() {
//        pnlMain.setSize(DISPLAY_TOP_WIDTH, DISPLAY_SCREEN_HEIGHT);
//        pnlMenu.setSize(DISPLAY_MENU_WIDTH, DISPLAY_MENU_HEIGHT);
//        pnlTitle.setSize(DISPLAY_TOP_WIDTH, DISPLAY_TOP_HEIGHT);
//        pnlContent.setSize(DISPLAY_CONTENT_WIDTH, DISPLAY_CONTENT_HEIGHT);
//        btnColapse.setVisible(false);
    }
    
    private void collapse() {
        if (!statusCollapseMenu) {
            pnlMenu.setSize(65, DISPLAY_SCREEN_HEIGHT);
            statusCollapseMenu = true;
        } else {
            pnlMenu.setSize(200, DISPLAY_SCREEN_HEIGHT);
            statusCollapseMenu = false;
        }
    }
    
    private void onClose() {
        System.exit(0);
    }
    
    private void showPage01() {
        PageUI01 page01 =new PageUI01();
        page01.setSize(DISPLAY_CONTENT_WIDTH, DISPLAY_CONTENT_HEIGHT);
        page01.setLocation(0, 0);
        
        pnlContent.removeAll();
        pnlContent.add(page01, BorderLayout.PAGE_START);
        pnlContent.revalidate();
        pnlContent.repaint();
    }
    
    private void showPage02() {
        PageUI02 page02 =new PageUI02();
        page02.setSize(DISPLAY_CONTENT_WIDTH, DISPLAY_CONTENT_HEIGHT);
        page02.setLocation(0, 0);
        
        pnlContent.removeAll();
        pnlContent.add(page02, BorderLayout.PAGE_START);
        pnlContent.revalidate();
        pnlContent.repaint();
    }
    
    @Override
    public void update(String action, Object data) {
        UIMain main = this;
        if ("open".equalsIgnoreCase(action)) {
            main.setVisible(true);
        } else {
            main.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnColapse = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlProfile = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(51, 153, 255));
        pnlMenu.setMaximumSize(new java.awt.Dimension(200, 32767));
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 720));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnColapse.setText("=");
        btnColapse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColapseActionPerformed(evt);
            }
        });

        jButton1.setText("Page 01");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Page 02");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pnlProfile.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addComponent(btnColapse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnColapse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 515, Short.MAX_VALUE)
                .addComponent(btnExit))
        );

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setPreferredSize(new java.awt.Dimension(1080, 720));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitle.setPreferredSize(new java.awt.Dimension(1080, 50));

        jLabel1.setText("Menu 1");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1028, Short.MAX_VALUE))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlMain.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlContent.setBackground(new java.awt.Color(255, 102, 102));
        pnlContent.setPreferredSize(new java.awt.Dimension(1080, 680));

        jLabel2.setText("Content 1");

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(1012, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(658, Short.MAX_VALUE))
        );

        pnlMain.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnColapseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColapseActionPerformed
        collapse();
    }//GEN-LAST:event_btnColapseActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        onClose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showPage01();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showPage02();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColapse;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables

}
