/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ulabs.appui01.ui.components.viewProfile;

import com.ulabs.appui01.ui.components.viewProfile.dto.ViewProfileDTO;
import com.ulabs.appui01.common.Util;
import com.ulabs.appui01.lib.router.EventListener;
import java.time.LocalDateTime;

/**
 *
 * @author manuelguarniz
 */
public class ViewUIProfile extends javax.swing.JPanel implements EventListener {
    
    public static int WIDTH = 188;
    public static int HEIGHT = 65;

    /**
     * Creates new form VUIProfile
     */
    public ViewUIProfile() {
        initComponents();
    }
    
    @Override
    public void update(String action, Object data) {
        if ("update".equalsIgnoreCase(action)) {
            ViewProfileDTO dto = (ViewProfileDTO) data;
            lblUserProfile.setToolTipText(dto.getUsername());
//            lblUserProfile.setText(Util.ellipsis(dto.getUsername(), 10));
            lblUserProfile.setText(dto.getUsername());
            if (dto.getLastConection() == null) {
                dto.setLastConection(LocalDateTime.now());
            }
            String date = Util.formatDate(dto.getLastConection());
            lblLastConnection.setToolTipText(date);
            lblLastConnection.setText(date);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUserProfile = new javax.swing.JLabel();
        lblLastConnection = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(188, 65));
        setPreferredSize(new java.awt.Dimension(188, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(188, 65));

        jLabel1.setText("Usuario:");

        jLabel2.setText("U. conexión:");

        lblUserProfile.setText("XXXX");
        lblUserProfile.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblLastConnection.setText("XXXX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblLastConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUserProfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLastConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLastConnection;
    private javax.swing.JLabel lblUserProfile;
    // End of variables declaration//GEN-END:variables

}
